### ISSUE TITLE
请求添加哔哩哔哩图标

### ISSUE THREAD

**Issue by bingo084** [elliana-wt/Pixel-Launcher-Icons#2]

**Comment by elliana-wt** [comment]
bilibili 我记得是适配的哇

![Screenshot_20240314-150823](https://github.com/elliana-wt/Pixel-Launcher-Icons/assets/35355832/8af0648d-17bf-48b8-a7a2-47019cb0e85b)

**Comment by bingo084** [comment]
应该是我的哔哩哔哩版本 7.50.0 低了，有营销信息

![Screenshot_20240314-151358_Pixel 启动器](https://github.com/elliana-wt/Pixel-Launcher-Icons/assets/71869774/f3ec8438-423f-4543-a0fa-cd6a7105e740)

升级到 7.70.0 正常了，暂时没有营销信息了

**Comment by elliana-wt** [comment]
估计我是 Play 版所以没有这个问题，不过我也加上吧。

**Comment by elliana-wt** [comment]
已经更新
